config/routes.rb
Compass::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]

  resources :articles

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, :counter_cache => true
  mount_uploader :image, ArticleUploader

  def user_name
    user.name
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  acts_as_tree
  has_many :articles
  has_many :users
  BASE_CACHE_KEY = "base_subject_key"

  scope :basic_subjects, where(:parent_id => nil)

  def self.cache_base_subject
    a = Rails.cache.read BASE_CACHE_KEY
    return a if !a.blank?
    result = []
    Subject.basic_subjects.each do |base_subject|
      temp_out_array  = []
      temp_out_array << base_subject.name
      temp_out_array << []
      base_subject.children.each do |child|
        temp_inner_array = []
        temp_inner_array << child.name
        temp_inner_array << child.id
        temp_out_array.last << temp_inner_array
      end
      result << temp_out_array
    end
    Rails.cache.write BASE_CACHE_KEY, result
    return result
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :subject_id, :avatar

  has_many :articles
  belongs_to :subject, :counter_cache => true

  mount_uploader :avatar, AvatarUploader

  def to_param
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  before_filter :initialize_article, :only => [:show, :edit, :udpate, :destroy]

  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end

  private
  def initialize_article
    @article = Article.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  -if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :comment_count
    = f.number_field :comment_count
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :digest
    = f.text_field :digest
  .field
    = f.label :image
    = f.file_field :digest
  .actions
    = f.submit 'Save'
javascript:
  $("#article_content").tinymce({
      //General options
  theme: "advanced",

  //Theme options
  theme_advanced_buttons1: "bold,link,unlink,removeformat",
  theme_advanced_buttons2: "",
  theme_advanced_buttons3: "",
  theme_advanced_toolbar_location: "top",
  theme_advanced_toolbar_align: "left",
  invalid_elements : "iframe,script"

  });

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
.container#main
  .span-13.colborder.prepend-3
    - @articles.each do |article|
      h2.ishinfo
        span.ishdata=article.created_at.strftime("%Y年 %m月 %d日")
      .item
        h3.title= link_to article.title, article_url(article)
        h4.byline
          |by
          =link_to article.user_name, user_url(article.user)
        blockquote.style1
          span=article.digest
        .content
          == article.content
        hr
        = link_to 'New Article', new_article_path, :class => "button positive"
  .span-4.append-3.last
    h2 test

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
.container#main
  .span-13.colborder#content.prepend-3.item
    h2.ishinfo
      span.ishdata=@article.created_at.strftime("%Y年 %m月 %d日")
    h3.title= link_to @article.title, article_url(@article)
    h4.byline
      |by
      = link_to @article.user_name, user_url(@article.user)
    ul#metastuff
      |所属专业
      =link_to "aa", article_url(@aricle)
      | ,
      =link_to "use", user_url(@article.user)
    .content.page
      ==@article.content
    = link_to 'Edit', edit_article_path(@article)
    '|
    = link_to 'Back', articles_path
  .span-4.last.append-3
    h2 Digest
    =@article.digest

app/views/home/index.html.slim
.container
  .span-7.colborder
    h1.alt aaa
    .page.bordered
      p.content.gradient
        |ffffff22fffffff
      p.content
        |ffffff22fffffff
      p.content
        |ffffff22fffffff
      p.content
        |当我们一起走过
  .span-7.colborder
    h2 ccc
    .container
      .span-3.colborder
        p ffffffffffff
      .span-3.last
        p fffffffffff
  .span-8.last
    h3 asdfasdf

app/views/layouts/application.html.slim
DOCTYPE html
html
  head
    title Compass
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body{class=params[:controller]}
    ul#navbar
      .container
        .prepend-3
          li#articles = link_to "ARTICLES", articles_url
          li#articles = link_to "ARTICLES", articles_url
          li#articles = link_to "ARTICLES", articles_url
          li#articles = link_to "ARTICLES", articles_url
          li#feed = link_to "ARTICLES", articles_url
    #ish
      span
    h1#masthead
      =link_to image_tag("alalogo.gif"), root_url
    = yield
    #footer
      p
        span.issn
          |ISSN:0724
        span.copyright
          |2008-2011 @xiaofushi